version: 0.2
phases:
  install:
    commands:
      - echo "install cypress dependencies..."
      - npm install cypress --save-dev
      - apt-get update
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - node_modules/.bin/cypress run 
      - echo "post_build step"
